app = "vote-system"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  BASE_URL = "https://vote-system.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines  = true
  min_machines_running= 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 120
    hard_limit = 160

[[vm]]
  cpu_kind = "shared"
  cpus     = 2          # 2 vCPU 추천
  memory_mb = 1024

[[mounts]]
  source = "data"
  destination = "/data"
