name: Build macOS App

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flask python-dotenv qrcode netifaces PyQt5

      - name: Create database and env file
        run: |
          python scripts/init_db.py  # 또는 init_database()를 포함한 별도 초기화 스크립트
          echo "ADMIN_PASSWORD=changeme123" > .env

      - name: Build macOS App with PyInstaller
        run: |
          pyinstaller \
            --windowed \
            --onedir \
            --name vote_system \
            --icon static/favicon.icns \
            --add-data "static:static" \
            --add-data "templates:templates" \
            --add-data ".env:." \
            --add-data "data.db:." \
            --add-data "log:log" \
            --add-data "server.py:." \
            launcher.py

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: vote_system-macOS
          path: dist/vote_system

