# .github/workflows/build-macos.yml
name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pyinstaller \
            flask \
            python-dotenv \
            qrcode \
            netifaces \
            requests \
            pillow \
            "PyQt5==5.15.*"   # ← 마지막 줄엔 \ 없이 따옴표로 감싸도 OK

      - name: Prepare environment
        run: |
          mkdir -p log
          python - <<'PY'
          from server import init_db
          init_db()
          PY
          echo "ADMIN_PASSWORD=changeme123" >> .env

      - name: Build macOS App with PyInstaller
        run: |
          pyinstaller \
            --windowed \
            --onedir \
            --name vote_system \
            --icon static/favicon.icns \
            --add-data "static:static" \
            --add-data "templates:templates" \
            --add-data ".env:." \
            --add-data "data.db:." \
            --add-data "log:log" \
            --add-data "server.py:." \
            launcher.py

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: vote_system-macOS
          path: dist/vote_system
