# .github/workflows/build-macos.yml
name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1) 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python 3.10 설치 + 캐시
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 3) 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pyinstaller flask python-dotenv qrcode netifaces requests \
            PyQt5==5.15.*  # macOS용 바이너리 배포본

      # 4) 환경 준비 (로그 폴더·DB·.env)
      - name: Prepare environment
        run: |
          mkdir -p log
          python - <<'PY'
          from server import init_db
          init_db()
          PY
          echo "ADMIN_PASSWORD=chairperson113@" >> .env

      # 5) PyInstaller 빌드
      - name: Build macOS App with PyInstaller
        run: |
          pyinstaller \
            --windowed \
            --onedir \
            --name vote_system \
            --icon static/favicon.icns \
            --add-data "static:static" \
            --add-data "templates:templates" \
            --add-data ".env:." \
            --add-data "data.db:." \
            --add-data "log:log" \
            --add-data "server.py:." \
            launcher.py

      # 6) 산출물 업로드
      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: vote_system-macOS
          path: dist/vote_system
